export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const SET_CURRENT_RECIPE = 'SET_CURRENT_RECIPE';

export const SHOW_RECIPE = 'SHOW_RECIPE';
export const HIDE_RECIPE = 'HIDE_RECIPE';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

